### ISSUE TITLE
Some questions about application of a trained policy on empirical data

### ISSUE THREAD

**Issue by anxixiang** [captain-project/captain-project#2]
Hello sir,

When I followed CAPTAIN notebooks 4. Application of a trained policy on empirical data  the notebook, an error was returned.
The previous codes were running smoothly.This error confused me.

trained_model_file ='trained_models/full_monitor_protect_at_once_d4_n8-0.log'
env_list, out_files = cn.run_policy_empirical(env,
                                              trained_model=trained_model_file,
                                              obsMode=1, # full species monitoring
                                              observePolicy=2, # recurrent monitoring, at-once protection
                                              n_nodes=[8, 0],
                                              budget=0.1,
                                              conservation_target=conservation_target, # apply conservation target
                                              stop_at_end_budget=True,
                                              seed=4321,
                                              update_features=100,
                                              result_file='output',
                                              replicates=3)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 2, in <module>
TypeError: run_policy_empirical() got an unexpected keyword argument 'conservation_target'

Additionally, I got an output file--empirical_data/output_4321.pkl, how can I view and analyse it?
Your reply will be appreciated and I am looking forward to desktop app of CAPTAIN very much!!!

Yours sincerely,
Nan

**Comment by dsilvestro** [comment]
Hi @anxixiang can you try running the version on the [dev branch](https://github.com/captain-project/captain-project/tree/dev)?

**Comment by anxixiang** [comment]
@dsilvestro  Thank you for your reply, I can now  run it successfully. 
But I can't read the output file(.pkl). How to get useful information from it? For example, which units are selected for protection. 
Or are there more steps that I have overlooked?

**Comment by dsilvestro** [comment]
Yep, I am working on a small function to help parsing that information - more soon!

**Comment by dsilvestro** [comment]
@anxixiang I just pushed some updates to the dev branch and [notebooks](https://github.com/captain-project/notebooks/blob/main/Analysis_empirical_data.ipynb) that show how to summarize the results using a new `summarize_policy_empirical` function that returns a Pandas data frame with the estimated priority for each planning unit (PU).

**Comment by anxixiang** [comment]
OK, I will try it. Many thanks.
